= Dice

Features::
* [x] Roll any amount of any-sided dice via notation `<no of dice>d<no of sides>` e.g. `3d6`, `1d20`.
* [x] Modifiers via `-`, `+`, `*`, `/` e.g. `2d6-2` gives results `0 through 10`.
* [x] Integer arguments to modifiers.
* [x] Dice notation arguments to modifiers.
* Default shorthand notations:
** [ ] `D` = `d6`
** [x] If amount of dice is not given, assume 1 dice.
* [ ] Verbose and silent modes i.e. display result of each die rolled.
* Advanced rolls:
** [ ] Flux e.g. `2d6` results `-5 through +5` (used in Traveller5)
** [ ] Negative Flux e.g. `2d6` results `-5 through 0` (used in Traveller5)
** [ ] Positive Flux e.g. `2d6` results `0 through +5` (used in Traveller5)
** [ ] Success threshold e.g. diceroll with threshold `7` will produce `success`
point every time a dice rolls a score of `7` or above.
** [ ] Success and fail threshold: in addition to the success threshold, each dice
rolled will produce a `failure` point if it rolls below or at the fail
threshold. (used in Vampire: The Masquerade 5th edition)
* [ ] Show probability for simple dice notations i.e. `<ammount>d<sides>`.
* [ ] Test dice rolls and display statistics.
